trigger:
- master
- feature/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  imageName: 'current-ip-api'
  appName: 'app-current-ip-api-prod'
  containerRegistry: 'asizikov'
  imageRepository: 'current-ip'
  tag: '$(Build.BuildId)'


steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet test --filter 'FullyQualifiedName!~FunctionalTests'
  displayName: 'run dotnet test'
- task: Docker@2
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  displayName: 'build and push to docker'
  inputs:
    containerRegistry: 'docker-hub-public'
    repository: 'asizikov/current-ip'
    command: 'buildAndPush'
    buildContext: .
    Dockerfile: 'src/CurrentIp.Web/Dockerfile'
- task: AzureWebAppContainer@1
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  displayName: 'deploy to Azure Web App Containers'
  inputs:
    azureSubscription: 'Free Trial (115fc1f7-b661-4a76-bb16-14e52ba3090f)'
    appName: $(appName)
    containers: $(containerRegistry)/$(imageRepository):$(tag)
